[package]
name = "mana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.32"
eq-float = "0.1.0"
tap = "1.0.1"
derive_more = "0.99.17"
